bpf: Make bpf_helper_defs.h c++ friendly
Compiling C++ BPF programs with existing bpf_helper_defs.h is not
possible due to stricter C++ type conversions. C++ complains
about (void *) type conversions:

$ clang++ --include linux/types.h ./tools/lib/bpf/bpf_helper_defs.h

bpf_helper_defs.h:57:67: error: invalid conversion from ‘void*’ to ‘void* (*)(void*, const void*)’ [-fpermissive]
   57 | static void *(*bpf_map_lookup_elem)(void *map, const void *key) = (void *) 1;
      |                                                                   ^~~~~~~~~~
      |                                                                   |
      |                                                                   void*

Extend bpf_doc.py to use proper function type instead of void.

Before:
static void *(*bpf_map_lookup_elem)(void *map, const void *key) = (void *) 1;

After:
static void *(*bpf_map_lookup_elem)(void *map, const void *key) = (void *(*)(void *map, const void *key)) 1;

v2:
- add clang++ invocation example (Yonghong)

Cc: Yonghong Song <yhs@meta.com>
Signed-off-by: Peng Wei <pengweiprc@google.com>
Signed-off-by: Stanislav Fomichev <sdf@google.com>
Acked-by: Yonghong Song <yhs@fb.com>
Link: https://lore.kernel.org/r/20230426155357.4158846-1-sdf@google.com
Cc: john.fastabend@gmail.com
Cc: haoluo@google.com
Cc: daniel@iogearbox.net
Cc: andrii@kernel.org
Cc: ast@kernel.org
Cc: jolsa@kernel.org
Cc: kpsingh@kernel.org
Cc: song@kernel.org
Cc: martin.lau@linux.dev
Cc: bpf@vger.kernel.org